### ISSUE TITLE
how can I use a custom font for syntax highlighting ?

### ISSUE THREAD

**Issue by ghost** [kuoa/julia#3]
Also, I'm unable to change the case of user name, its always in capital.

**Comment by kuoa** [comment]
Hello @somu1795 !

To modify styling and highlight colors for the syntax highlighting you can edit `/_sass/_syntax.scss`. You can change the colors and use your own font.

I'm not sure I understand your second question, but take a look at `/_sass/_layout.scss` and search for the `uppercase` value. This should give you a starting point for changing what you are looking for.

**Comment by ghost** [comment]
Thanks, and is there any way to use a custom font , apart from google fonts?
Do I have to use `@font-face`?

**Comment by kuoa** [comment]
Exactly, you need to use `@font-face` :+1:
